plugin 'cocoapods-use-frameworks-dynamic-wrapper'

target 'simpleExample' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks! :dynamic_wrapper => true

  project 'simpleExample.xcodeproj'

  pod 'AppleDY', :path => './Modules/AppleDY/AppleDY.podspec', :inhibit_warnings => true
  pod 'Apple', :path => './Modules/Apple/Apple.podspec'

  pod 'AFNetworking'
  # Pods for simpleExample

  target 'simpleExampleTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'simpleExampleUITests' do
    # Pods for testing
  end

end
